name: Python Matrix Operations

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Run Python script
      run: python file.py


  secrets-example:
    needs: build
    runs-on: ubuntu-latest
    if: ${{always()}}

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: use a secret variable
        env: 
          SECRET_TOKEN: ${{secrets.my_secret_token}}
        run: |
          echo "The secret is $SECRET_TOKEN"